### ISSUE TITLE
Trigger event at specific percentage view of the component

### ISSUE THREAD

**Issue by scazzy** [stutrek/scrollmonitor-react#16]
I'm able to trigger enter exit events, or the above/below events.
But I'm looking to trigger an event when scrolled, say, 75% or height of the component view.
How can I implement that?

I was able to trigger it, but the stateChange event wouldn't fire until one of the predefined events occured

**Comment by stutrek** [comment]
It's missing from the documentation, but you can pass an offsets prop to your component.

https://github.com/stutrek/scrollMonitor#offsets

**Comment by scazzy** [comment]
@stutrek I tried the offsets but it didn't seem to work properly. Problems I faced is that it didn't trigger correct events based on offset given>
I'm trying to implement infinite scroll, and have attached `scrollMonitor` to the wrapper component. I have set `offsets{{bottom: -500}}` (to trigger when scroll reaches contentheight - 500px). Have given the data load call in onStateChange with a filter of `container.contentHeight - container.viewportBottom <= 500`, just to avoid extra triggers.

Or have I not use offsets correctly? Or something like I need to explicitly tell scrollMonitor that extra content has been added? or missing something else?

![image](https://user-images.githubusercontent.com/1681586/29916593-d4c336f8-8e5c-11e7-98b1-8173f9b55453.png)
// Where preloadOffsetHeight = -500


```
// On state change
if(container.contentHeight - container.viewportBottom <= 500) {
    // Load next content
}
```

**Comment by scazzy** [comment]
It was a crazy thing. The scroll monitor would attach to the initial DOM element which was <loading> instead of the actual content.
I've moved the loading handler outside the watched component. But yeah, any way to tell scrollMonitor that the content has changed, just in case?

I'm closing this thing. Great lib!

**Comment by stutrek** [comment]
`this.props.scrollContainer.recalculateLocations()` will update the size. It will automatically do so on the next scroll/resize event if the height of the document/scroll container changes.
