### ISSUE TITLE
React 16

### ISSUE THREAD

**Issue by bartels** [stutrek/scrollmonitor-react#18]
peerDependencies currently specify react 15 currently. Can this be updated for react 16?

**Comment by alex-robert-dev** [comment]
@stutrek Hi. Can you tell me if you have planned to further develop / maintain this component? Thanks

**Comment by stutrek** [comment]
I do plan on it, and I'm currently working on upgrading to React 16 at my job. Sorry for the delay.

**Comment by stutrek** [comment]
If you can send me a PR it will accept it and it'll be done much faster. I am very busy in my work and personal lives right now. Thanks

**Comment by stutrek** [comment]
fixed in 2.3.2

**Comment by alex-robert-dev** [comment]
@stutrek Great, Thanks!
