### ISSUE TITLE
Change offset values dynamically

### ISSUE THREAD

**Issue by paulinhapenedo** [stutrek/scrollmonitor-react#19]
Hi there!

I'm using this awesome lib in a project and I have a special use case. I have different offsets based on different viewports (mobile, tablet and desktop). When testing on an iPad, for instance, I go from a tablet viewport to a desktop viewport because of the breakpoints (1024px).

Right now, I'm doing the viewport measurement on `componentDidMount` and using that to update the offsets object saved in the component's state. That gets passed down to the watched component. I thought that this would work but seems like `scrollmonitor` doesn't expect new `offsets` value to be sent, so even when the `recalculateLocation` is triggered, the lib is still using the old offsets value.

Is there a way of doing that? If not, is it ok if I open a PR with that kind of feature?

Thanks!

**Comment by stutrek** [comment]
This is probably a use case I wasn't expecting. PRs are welcome!
