### ISSUE TITLE
Doesn't run after install

### ISSUE THREAD

**Issue by RussMax783** [stutrek/scrollmonitor-react#2]
Hey, excited to use this package, but i can't seem to get it working. When webpack tries to compile it gives me this error:

```
Error in ./~/scrollmonitor-react/index.js
Module parse failed: /<PATH>/node_modules/scrollmonitor-react/index.js Unexpected token (54:10)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (54:10)
 @ ./src/components/my-component.js 27:26-56
```

(where <PATH> is the path to node modules)

I've tried changing the index.js to include `"jsnext:main": "index.js",`
and `"main": "dist/index.js",` But that also throws an error saying scrollMonitor is undefined. 

I've verified scroll monitor is installed and tried messing with a couple things but still couldn't get it to run.

**Comment by stutrek** [comment]
Are you working on something small that I could clone and try out?

What version of Node are you on?

**Comment by RussMax783** [comment]
Node: v6.7.0

unfortunately its a pretty large project that i cant do that... But here is what i've found...

I copied your index.js file and put it into my own component and it worked.  So im pretty sure it has something to do with your build.

putting `"main": "dist/index.js"` in your package.json will point to make sure everyone is using the build you have in `dist`. 

Like i said above, when i am able to run `dist/index.js` i get scrollMonitor is not defined, and looking at [index.js line 175](https://github.com/stutrek/scrollmonitor-react/blob/master/dist/index.js#L175), scrollMonitor is not defined anywhere. Maybe because you're marking scrollmonitor as an external? [in webpack.config.js](https://github.com/stutrek/scrollmonitor-react/blob/master/webpack.config.js#L22)

**Comment by zacanger** [comment]
Minimal example: https://github.com/zacanger/scrollmonitor-react-issue-2

**Comment by zacanger** [comment]
Removing the [externals obj](https://github.com/stutrek/scrollmonitor-react/blob/master/webpack.config.js#L22) and running `webpack` builds as expected. Not sure what the intention is with those options, but unless I misunderstand `externals`, I think that would only work if React, ReactDOM, and scrollMonitor were exposed on `window`?

**Comment by stutrek** [comment]
That's it. The externals lets webpack build it without including the files, but that's not the solution I should have used.

**Comment by stutrek** [comment]
Thanks @RussMax783 and @zacanger, the new version is pure babel and I took your minimal breaking case and added it to the repo as a simple test.

You can make scroll containers now too, so you'll have to `import { Watch } from 'scrollmonitor-react'`. Version bump to 2.0 too, since it's a breaking change.

Thanks again for your help.

**Comment by zacanger** [comment]
Thanks very much!
