### ISSUE TITLE
initial load with elements in view are set to wrong state

### ISSUE THREAD

**Issue by RussMax783** [stutrek/scrollmonitor-react#3]
Everything (isInViewport, isAbove...) defaults to false. When an element loads, if its in the viewport, the corresponding states do not change to their correct state until you scroll those elements out of view and then back in.   

I've tries creating a function

```
updateState = () => {
  this.setState({
        isInViewport: this.watcher.isInViewport,
        isAboveViewport: this.watcher.isAboveViewport,
        isBelowViewport: this.watcher.isBelowViewport,
        isFullyInViewport: this.watcher.isFullyInViewport
      })
    }
```

that is called by `this.watcher.on('stateChange', this.updateState)` 

and then also calling it in the componentDidMount. This sets the states to the correct state, but right when you scroll, will change them back to all false, and will only change them back to the correct state when you scroll all the way to the top.

**Comment by stutrek** [comment]
Fixed in the new version, but you'll have to `import { Watch } from 'scrollmonitor-react'` because I also added containers.
