### ISSUE TITLE
questions regarding offsets

### ISSUE THREAD

**Issue by RussMax783** [stutrek/scrollmonitor-react#4]
Hello again, Let me explain our use case that i am trying to use scroll monitor for, and then ask a question. (sorry, this may belong in the scrollMonitor repo)

We have a huge list of images/elements that are rendered in a grid. We want to use scroll monitor to detect when an element is fully in view, to send an analytics event saying that a specific element was in the users viewport. We also want to pre-load the images for the items that are about to come into view so that they will load before the element is in view as the user is scrolling. So if we had a 500 - 1000 pixel padding we would say "render this item because its now about to come into view, but don't send an analytic event because the user hasn't seen it yet".  This could happen both with items below, and items above. (but items above will have already retrieved images from the server. 

I've tried messing with offsets but the problem is that it skews the whole element being watched, so the `isInView` might be correct and we could start loading the image, but the `isFullyInView` is incorrect, because if the element is stretched enough, to say 500px, there is a very small window that in the middle of the view port that would be considered "Fully in view". 

See the following image, where green is marked as `isFullyInViewport` and the red is just `isInViewport`

![image](https://cloud.githubusercontent.com/assets/5333786/21160863/a947c872-c143-11e6-8871-9c21a608fcfe.png)

I would like to not have to fork scrollmonitor and change one line of code just for this use case, so i thought I would ask and see if you have used it for this before. Or if you know of a way that we could offset for `isInView` and not for `isFullyInView`. 

Any sort of feedback would be super awesome!

**Comment by stutrek** [comment]
Can you just put two watchers on the same element?

**Comment by RussMax783** [comment]
Ah,  Would not have thought of that.  That worked.  I had to put the watcher with the offset outside another watcher with 0 offset. But one catch was that i had to explicitly say what props to send down to the wrapped component, because if i just passed `...this.props`  into both components, the outer props of isInViewport would override the inner one. (hope that makes sense)

Thanks a bunch for your quick feedback
